name: CI

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
      PYPI_TOKEN:
        required: true

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.9"
      - name: Load cached Poetry installation
        uses: actions/cache@v4.0.2
        with:
          path: ~/.local # the path depends on the OS
          key: dotlocal-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-0 # increment to reset cache
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4.0.2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Run all pre-commit hooks
        run: |
          source $VENV
          pre-commit run --all-files

  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.5.1

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Load cached Poetry installation
        uses: actions/cache@v4.0.2
        with:
          path: ~/.local # the path depends on the OS
          key: dotlocal-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-0 # increment to reset cache
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4.0.2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Test with Pytest
        run: |
          source $VENV
          pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    # Avoid publishing to PyPI from the template workflow
    env:
      NO_PYPI: ${{ vars.NO_PYPI }}
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    environment: release
    needs:
      - test
      - lint
      - commitlint

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      # Do a dry run of PSR
      - name: Test release
        uses: python-semantic-release/python-semantic-release@v9.8.1
        if: github.ref_name != 'main'
        with:
          root_options: --noop

      - name: Release
        id: release
        if: github.ref_name == 'main'
        uses: python-semantic-release/python-semantic-release@v9.8.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        # NOTE: DO NOT wrap the conditional in ${{ }} as it will always evaluate to true.
        # See https://github.com/actions/runner/issues/1173
        if: ${{ (env.NO_PYPI == '') && (steps.release.outputs.released == 'true') }}
        with:
          password: ${{ secrets.PYPI_TOKEN }}
